"use client";
import { Button } from "@/components/ui/button";
import { formatFileName } from "@/lib/utils";
import { Download } from "lucide-react";

export function DownloadSummaryButton({
  title,
  summaryText,
  fileName,
  createdAt,
}: {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}) {
  const handleDownload = () => {
    if (!summaryText) return;

    const summaryContent = `# ${formatFileName(title)}
Generated Summary
Generated on: ${new Date(createdAt).toLocaleDateString("en-IN", {
        year: "numeric",
        month: "short",
        day: "numeric",
      })}
      
${summaryText}
      
Original File: ${fileName}
Generated by Summarizer.AI
      `;

    const blob = new Blob([summaryContent], {
      type: "text/plain;charset=utf-8",
    });

    const url = URL.createObjectURL(blob);

    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `Summary-${title}.txt`;

    document.body.appendChild(anchor);
    anchor.click();
    document.body.removeChild(anchor);

    URL.revokeObjectURL(url);
  };

  return (
    <Button
      size="sm"
      className="h-8 px-3 bg-rose-100 text-rose-600 hover:text-rose-700 hover:bg-rose-50"
      onClick={handleDownload}
    >
      <Download className="h-4 w-4 mr-1" />
      Download Summary
    </Button>
  );
}
